### ISSUE TITLE
Link wled web view

### ISSUE THREAD

**Issue by bewee** [tim-hellhake/wled-adapter#2]
First of all: Thanks for adding the MDNS-less configuration variant😊

I think it would be nice to have the thing link to the web view hosted by the ESP, but failed to get this done: It seems not to find the `addLink` function, although this one seems to exist? ([https://github.com/WebThingsIO/gateway-addon-node/blob/master/src/device.ts](https://github.com/WebThingsIO/gateway-addon-node/blob/master/src/device.ts)). And I also failed to import the affiliated Link type :/

**Comment by tim-hellhake** [comment]
> It seems not to find the addLink function, although this one seems to exist? (https://github.com/WebThingsIO/gateway-addon-node/blob/master/src/device.ts). And I also failed to import the affiliated Link type :/

It's not part of `1.0.0`.
You can cast it to `any` for know.
As soon as the new gateway version is released we can update the `gateway-addon` lib to `1.1.0`.

**Comment by tim-hellhake** [comment]
Resolved by #3
